# <font color=red> CODE CHALLENGES </font>
---
### Instruction
1. Push your solutions to your github account.
3. Deadline is before finals.
---
1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.
2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.
3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.
4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.
5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

In [1]:
import numpy as np

def numberOne(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    # Check if the matrices have the same dimensions
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")

    result = matrix1 + matrix2

    step_operations = [f"matrix1 + matrix2:\n{result}"]

    return result, step_operations
    
matrix1 = [[2, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result, step_operations = numberOne(matrix1, matrix2)

# Print the original matrices
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Print the result matrix
print("\nResult:")
for row in result:
    print(row)

Matrix 1:
[2, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Result:
[11 10 10]
[10 10 10]
[10 10 10]


In [2]:
def numberTwo(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("The number of columns in matrix1 must be equal to the number of rows in matrix2 for multiplication.")

    result = np.dot(matrix1, matrix2)

    step_operations = [f"matrix1.dot(matrix2):\n{result}"]

    return result, step_operations

matrix1 = [[2, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result, step_operations = numberTwo(matrix1, matrix2)

# Print the original matrices
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Print the result matrix
print("\nResult:")
for row in result:
    print(row)

Matrix 1:
[2, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Result:
[39 32 25]
[84 69 54]
[138 114  90]


In [5]:
def numberThreeAddition(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions.")

    result = matrix1 + matrix2

    return result
    
matrix1 = [[2, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result = numberThreeAddition(matrix1, matrix2)

# Print the original matrices
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Print the result matrix
print("\nResult:")
for row in result:
    print(row)

Matrix 1:
[2, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Result:
[11 10 10]
[10 10 10]
[10 10 10]


In [2]:
def numberThreeAddition(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions.")

    result = matrix1 + matrix2

    return result

def numberThreeScalar(scalar, matrix):
    matrix = np.array(matrix)

    result = scalar * matrix

    return result

In [3]:
from Assignment3 import numberThreeAddition
from Assignment3 import numberThreeScalar

matrix_A = [[1, 2], [3, 4]]
matrix_B = [[5, 6], [7, 8]]

# Scalar value k
k = 2

# Demonstrating k(A + B) = kA + kB
result_k_times_A_plus_B = numberThreeScalar(k, numberThreeAddition(matrix_A, matrix_B))
result_kA_plus_kB = numberThreeAddition(numberThreeScalar(k, matrix_A), numberThreeScalar(k, matrix_B))



print("kA + kB:")
for row in result_kA_plus_kB:
    print(row)
    
print("\nk(A + B):")
for row in result_k_times_A_plus_B:
    print(row)
    
print("\nEquation: k(A + B) = kA + kB")

kA + kB:
[12 16]
[20 24]

k(A + B):
[12 16]
[20 24]

Equation: k(A + B) = kA + kB


In [5]:
def numberFour(matrix):
    matrix = np.array(matrix)

    if not matrix.size:
        return []

    # Check if the matrix is square (equal number of rows and columns)
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square to extract the diagonal.")

    diagonal = np.diagonal(matrix)

    return diagonal

In [6]:
from Assignment3 import numberFour
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("Original Matrix:")
for row in matrix:
    print(" ".join(map(str, row)))

result = numberFour(matrix)

print("\nDiagonal elements:", result)

Original Matrix:
1 2 3
4 5 6
7 8 9

Diagonal elements: [1 5 9]


In [7]:
def numberFive(matrix):
    matrix = np.array(matrix)

    if not matrix.size:
        return 0

    # Check if the matrix is square (equal number of rows and columns)
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square to calculate the trace.")

    trace = np.trace(matrix)

    return trace

In [8]:
from Assignment3 import numberFive

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Matrix:")
for row in matrix:
    print(" ".join(map(str, row)))
addition_of_diagonal = sum(matrix[i][i] for i in range(len(matrix)))
print("\nAddition of diagonal elements:", " + ".join(str(matrix[i][i]) for i in range(len(matrix))) + " = " + str(addition_of_diagonal))
result = numberFive(matrix)
print("Trace of the matrix:", result)

Matrix:
1 2 3
4 5 6
7 8 9

Addition of diagonal elements: 1 + 5 + 9 = 15
Trace of the matrix: 15


# <font color=red> Problem Solving </font>
---
Instructions
1. Write your solution in latex.
2. Push your solutions to your github account.
3. Deadline is before finals.
---
1. Solve $X$ given that:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix},
B =
\begin{bmatrix}
-1 & 0 \\
1 & 1 \\
\end{bmatrix}
\end{equation}
- $3X = A-2B$
- $2(A-B+2X) = 3(X-B)$
<br>
<br>

Solve for X in the equation $3X = A-2B$:

 \
     2B = \begin{bmatrix} -2 & 0 \\ 2 & 2 \end{bmatrix}
     

\
     A - 2B =
     \begin{bmatrix}
     3 & 2 \\
     1 & 2 \\
     \end{bmatrix}
     

 \
    X =
     \begin{equation}
      \frac{1}{3} \times
     \begin {bmatrix} 
     3 & 2 \\
     1 & 2 \\
     \end{bmatrix}
     =
     \begin{bmatrix}
     1 & \frac{2}{3} \\
     \frac{1}{3} & \frac{2}{3} \\
     \end{bmatrix}
     \end{equation}
     

 \
     Final Answer =
     \begin{equation}
      X = 
     \begin{bmatrix}
     1 & \frac{2}{3} \\
     \frac{1}{3} & \frac{2}{3} \\
     \end{bmatrix}
     \end{equation}
     

In [6]:
# Python Solution
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])

result = A - 2 * B

result = result / 3

print("result =",result)

result = [[1.         0.66666667]
 [0.33333333 0.66666667]]


Solve for X in the equation 2(A-B+2X) = 3(X-B):



Distributing the scalars:

2A - 2B + 4X = 3X - 3B
2A + X = -B
X = -B - 2A

Substitute:

 \
     -2A = \begin{bmatrix} -2 & 4 \\ 6 & 8 \end{bmatrix}

 \
     -B = \begin{bmatrix} 1 & 0 \\ -1 & -1 \end{bmatrix}

 \
     -B - 2A = \begin{bmatrix} -1 & -4 \\ -7 & -9 \end{bmatrix}

 \
     Final Answer =
     \begin{equation}
      X = 
     \begin{bmatrix}
     -1 & -4 \\
     -7 & -9 \\
     \end{bmatrix}
     \end{equation}
     

In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])


x = 2 * B - 2 * A - 3 * B

print("result =",x)

result = [[-1 -4]
 [-7 -9]]


2. Write B as a linear combination of the other matrices, if possible.
- 
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 2 \\
-1 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
2 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
<br><br>
- 
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix},
A_3 =
\begin{bmatrix}
1 & -1 \\
1 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
<br>
<br>

$$
B = c_1A_1 + c_2A_2
$$

Solving for $c_1$ and $c_2$ via systems of linear equations:

$$
\begin{align*}
2 &= c_1 \cdot 1 + c_2 \cdot 0 \\
5 &= c_1 \cdot 2 + c_2 \cdot 1 \\
0 &= c_1 \cdot (-1) + c_2 \cdot 2 \\
3 &= c_1 \cdot 1 + c_2 \cdot 1
\end{align*}
$$

Solving for $c_1$:

$$
\begin{align*}
2 &= c_1 \quad \Rightarrow \quad c_1 = 2
\end{align*}
$$

Solving for $c_2$:

$$
\begin{align*}
5 &= 2c_1 + c_2 = 2 \cdot 2 + c_2 \quad \Rightarrow \quad c_2 = -4
\end{align*}
$$

So, $\boxed{c_1 = 2,\ c_2 = -4}$, and we have:

$$
B = 2A_1 - 4A_2
$$


3. Given the following:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
2 & 6 \\
\end{bmatrix},
b_1 =
\begin{bmatrix}
3 \\
5 \\
\end{bmatrix},
b_2 =
\begin{bmatrix}
-1 \\
2 \\
\end{bmatrix},
b_3 =
\begin{bmatrix}
2 \\
0 \\
\end{bmatrix}
\end{equation}
- Find $A^{-1}$, and use this to solve for $Ax=b_1,Ax=b_2,Ax=b_3$
- Solve all three linear systems by row reducing the augmented matrix:
\begin{equation}
\begin{bmatrix}
\begin{array}{c|ccc}
A &
b_1 &
b_2 &
b_3 \\
\end{array}
\end{bmatrix}
\end{equation}

$A^{-1} = (\frac{1}{det(A)}) * 
\begin{bmatrix}
d & -b \\
-c & a \\
\end{bmatrix} \\
det(A) = (1 * 6) - (2 * 2) = 6 - 4 = 2 \\
A^{-1} = (\frac{1}{2}) * 
\begin{bmatrix}
6 & -2 \\
-2 & 1 \\
\end{bmatrix}
=
\begin{bmatrix}
3 & -1 \\
-1 & \frac{1}{2} \\
\end{bmatrix} \\
A | b_1 = \begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 3 \\
2 & 6 & 5 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-2\text{R}_{1}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 3 \\
0 & 2 & -1 \\
\end{array}\end{bmatrix}
\xrightarrow{\frac{1}{2}R_2}
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 3 \\
0 & 1 & -0.5 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 0 & 4 \\
0 & 1 & -0.5 \\
\end{array}\end{bmatrix} \\
\boxed{A | b_1: x_1 = 4, x_2 = -0.5} \\
A | b_2 = \begin{bmatrix}\begin{array}{cc|c}
1 & 2 & -1 \\
2 & 6 & 2 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-2\text{R}_{1}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & -1 \\
0 & 2 & 4 \\
\end{array}\end{bmatrix}
\xrightarrow{\frac{1}{2}R_2}
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & -1 \\
0 & 1 & 2 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 0 & -5 \\
0 & 1 & 2 \\
\end{array}\end{bmatrix} \\
\boxed{A | b_2: x_1 = -5, x_2 = 2} \\
A | b_3 = \begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 2 \\
2 & 6 & 0 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-2\text{R}_{1}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 2 \\
0 & 2 & -4 \\
\end{array}\end{bmatrix}
\xrightarrow{\frac{1}{2}R_2}
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 2 \\
0 & 1 & -2 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 0 & 6 \\
0 & 1 & -2 \\
\end{array}\end{bmatrix} \\
\boxed{A | b_3: x_1 = 6, x_2 = -2} \\
$

4. In each given, determine if $b$ is in $col(A)$, and $w$ is in $row(A)$
- 
\begin{equation}
A =
\begin{bmatrix}
1 & 0 & -1 \\
1 & 1 & 1 \\
\end{bmatrix},
b =
\begin{bmatrix}
3 \\
2 \\
\end{bmatrix},
w =
\begin{bmatrix}
-1 &
1 &
1
\end{bmatrix},
\end{equation}

\begin{align*}
Ax &= b \\
\Rightarrow \quad \begin{bmatrix}
1 & 1 & -1 \\
1 & 3 & 0 \\
3 & -1 & -5
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
&= \begin{bmatrix}
1 \\
2 \\
1
\end{bmatrix} \\
\Rightarrow \quad \begin{bmatrix}
x_1 + x_2 - x_3 &= 1 \\
x_1 + 3x_2 &= 2 \\
3x_1 - x_2 - 5x_3 &= 1
\end{bmatrix}
\end{align*}
\begin{align*}
\\x^T A &= w^T \\
\Rightarrow \qquad
\begin{pmatrix}
x_1 \\
x_2 \\
x_3
\end{pmatrix}^T
\begin{pmatrix}
1 & 1 & -1 \\
1 & 3 & 0 \\
3 & -1 & -5
\end{pmatrix}
&= \begin{pmatrix}
1 &
-3 &
-3
\end{pmatrix}^T \\
\Rightarrow \quad \begin{bmatrix}
x_1 + 3x_2 - 5x_3 &= 1 \\
x_1 + x_2 + x_3 &= -3 \\
-x_1 - x_2 - 3x_3 &= -3
\end{bmatrix}
\end{align*}
vector b is in the column space of A, and vector w is in the row space of A

5. Find the rank and nullity of:
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
6 & 3 & 5 & 1 & 0 \\
1 & 0 & 2 & 2 & 5 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix},

$$
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
6 & 3 & 5 & 1 & 0 \\
1 & 0 & 2 & 2 & 5 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2}-3\text{R}_{1}}
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
0 & -9 & 5 & 1 & -3 \\
1 & 0 & 2 & 2 & 5 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
\xrightarrow{\text{R}_{3}-\frac{1}{2}R_1}
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
0 & -9 & 5 & 1 & -3 \\
0 & -2 & 2 & 2 & 4 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
\xrightarrow{-\frac{1}{9}R_2}
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
0 & 1 & -\frac{5}{9} & -\frac{1}{9} & \frac{1}{3} \\
0 & -2 & 2 & 2 & 4 \\
0 & 4.5 & -1.5 & 0.5 & 1.5 \\
\end{bmatrix}
\xrightarrow{\text{R}_{3} + 2{R}_{2}, \ \text{R}_4 + \frac{9}{2}R_2}
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
0 & 1 & -\frac{5}{9} & -\frac{1}{9} & \frac{1}{3} \\
0 & 0 & \frac{4}{9} & \frac{4}{9} & \frac{10}{3} \\
0 & 0 & 0 & 0 & 0 \\
\end{bmatrix}
$$


$\text{Rank of the matrix= 3
Nullity = 2}$
