In [4]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [3]:
import numpy as np
A = np.array([[1,-1,1,4],[0,2,2,3],[2,0,1,2],[0,0,0,0],[0,0,0,0]]) 

def backwardSubstitution(A):
    m, n = A.shape  # m is the number of rows, n is the number of columns

    # Erase zero rows
    while m > 0 and np.all(A[m-1, n-2:] == 0):
        m -= 1

    # Check for zero or infinite solutions
    if m == 0:
        return "No solution."
    elif n - 1 > m:
        return "Infinite solutions."

    solutions = np.zeros(m)

    for j in range(m - 1, -1, -1):
        row_coefficients = A[j, :-1]
        constant_term = A[j, -1]

        # Check if the coefficient of the current unknown variable is zero
        if np.all(row_coefficients == 0):
            return "No unique solution."

        # Compute the current unknown variable value
        result = np.dot(solutions, row_coefficients)
        solutions[j] = (constant_term - result) / row_coefficients[j]

    return solutions

# Example usage with the provided matrix A
result = backwardSubstitution(A)
print(result)

[ 1.5 -0.5  2. ]


# More Examples
---
Solve the equation
$
\begin{equation}
x_1-x_2+x_3=3 \\
2x_1+x_2+8x_3 = 18 \\
4x_1+2x_2-3x_3 = -2 \\
\end{equation}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    2 & 1 & 8 &\bigm| & 18 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3}-2\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{-1}{19}\text{R}_{3}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
$
<br><br>
The system of equation has the solution:
$
\begin{equation}
x_1-x_2+x_3=3 \\
x_2+2x_3 = 4 \\
x_3 = 2 \\
\end{equation}
$
<br>
Performing back substitution yields:
$
\begin{equation}
x_1-x_2+x_3=3 \to x_1-0+2 = 3 \to x_1 = 3-2 = 1 \\
x_2+2x_3 = 4 \to x_2+2(2)=4 \to x_2+4=4 \to x_2 = 4-4 =0 \\
x_3 = 2 \\
\end{equation}
$
<br>
$\therefore \ x_1=1, x_2=0, x_3=2$

In [5]:
# using pythonic solutions
import numpy as np
A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

# Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

# Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

# Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

# Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

# Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')
print("Use your assignment for the backward substitution to find the solutions.")

# Assignment 1
print("Solutions x1, x2, x3:")
print(backwardSubstitution(A5))

A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

Use your assignment for the backward substitution to find the solutions.
Solutions x1, x2, x3:
[1. 0. 2.]


# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---
1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$ <br>
  $\cos{\theta}x+4y+z = \sqrt{3}$ does not follow the structure $a_1x_1+a_2x_2+a_3x_3 = b$ due to the inclusion of the trigonometric function ${\theta}$ and the presence of the constant $\sqrt{3}$,  hence, it does not qualify as a linear equation.<br>
- $cos{x}4y+z = \sqrt{3}$ <br>
  $cos{x}4y+z = \sqrt{3}$ this does not conform to the structure $a_1x_1+a_2x_2+a_3x_3 = b$ because of the involvement of the trigonometric function $x$ and the existence of the constant $\sqrt{3}$, thereby excluding it from being categorized as a linear equation.<br>
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ <br>
  $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ doesn't adhere to the form $a_1x_1+a_2x_2+a_3x_3 = b$ due to the presence of the trigonometric function $\frac{\pi}{2}$ and the inclusion of the non-linear term $x^{-1}$, thereby disqualifying it as a linear equation.<br>
- $x^1+y^1+z^1=0$ <br>
  $x^1+y^1+z^1=0$ is of the form $a_1x_1+a_2x_2+a_3x_3 = b$ since both the constant and the coefficients multiplied by a variable in the equation are raised to the power of 1; thus, it qualifies as a linear equation.
---
2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$ <br>
  Solution:<br>
a. We need to transform the linear equation into an augmented matrix, so<br> 
let: $x_2 = s$ <br> the new equation becomes: $2x_1+3s =5$.<br>
b. Solving for $x_1$ yields $x_1 = \frac{5-3s}{2}$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 &\bigm| & \frac{5-3s}{2} \\
    0 & 1 &\bigm| & s \\
\end{pmatrix}<br>
<br>
- $4x_1+3x_2+2x_3=1$ <br>
Solution:<br>
a. We need to transform the linear equation into an augmented matrix, so<br> 
let: $x_2 = s$ <br> $x_3 = t$ <br> the new equation becomes: $4x_1+3s+2t=1$.<br>
b. Solving for $x_1$ yields $x_1 = \frac{1-3s-2t}{4}$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{1-3s-2t}{4} \\
    0 & 1 & 0 &\bigm| & s \\
    0 & 0 & 1 &\bigm| & t \\
\end{pmatrix}<br>
<br>
- $3x-6y=0$ <br>
  Solution:<br>
a. We need to transform the linear equation into an augmented matrix, so<br> 
let: $y = s$ <br> the new equation becomes: $3x-6s =0$.<br>
b. Solving for $x$ yields $x = 6s$.<br>
c. The augmented matrix is of the form:
\begin{pmatrix}
    1 & 0 &\bigm| & 2s \\
    0 & 1 &\bigm| & s \\
\end{pmatrix}<br>
<br>

---
3. Solve the following systems of linear equations<br>
a.<br>
\begin{align}
x-y=0 \\
2x+y = 3
\end{align}
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    2 & 1  &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 3  &\bigm| & 3 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 3  &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 1  &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 &\bigm| & 0 \\
    0 & 1  &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1  &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x=1 \\
y=1
\end{align}
---

In [39]:
# Pythonic solution:
import numpy as np

A = np.array([[1, -1, 0], [2, 1, 3]])


A1 = RowAdd(A, 0, 1, -2)
print("A1")
print(A1,'\n')
A2 = RowScale(A, 1, 1/3)
print("A2")
print(A2,'\n')
A3 = RowAdd(A, 1, 0, 1)
print("A3")
print(A3,'\n')


print("Solutions x, y:")
print(backwardSubstitution(A3))

A1
[[ 1. -1.  0.]
 [ 0.  3.  3.]] 

A2
[[ 1. -1.  0.]
 [ 0.  1.  1.]] 

A3
[[1. 0. 1.]
 [0. 1. 1.]] 

Solutions x, y:
[1. 1.]


b. <br>
\begin{align}
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
\end{align}
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1  &\bigm| & -5 \\
    2 & 4  &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6  &\bigm| & -6 \\
    2 & 4  &\bigm| & 4 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6  &\bigm| & -6 \\
    2 & 4  &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6  &\bigm| & -6 \\
    0 & -6  &\bigm| & 6 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6  &\bigm| & -6 \\
    0 & -6  &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1  &\bigm| & -1 \\
    0 & -6  &\bigm| & 6 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1  &\bigm| & -1 \\
    0 & -6  &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1  &\bigm| & -1 \\
    0 & -6  &\bigm| & 6 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1  &\bigm| & -1 \\
    0 & -6  &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 6\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1  &\bigm| & -1 \\
    0 & 0  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x=4 \\
y=-1
\end{align}


In [51]:
# Pythonic solution:
import numpy as np
A = np.array([[1,5,-1],[-1,1,-5],[2,4,4]])


A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,1/6)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-5)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,6)
print("A5")
print(A5,'\n')


print("Solutions x, y:")
print(backwardSubstitution(A5))

A1
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]] 

A2
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 0. -6.  6.]] 

A3
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

A4
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

A5
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]] 

Solutions x, y:
[ 4. -1.]


c. <br>
\begin{align}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{align}
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1  &\bigm| & 0 \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    1 & 0 & 1  &\bigm| & 0 \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    1 & 0 & 1  &\bigm| & 0 \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & -\frac{3}{2} & \frac{3}{2}  &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
\xrightarrow{-\frac{2\text{R}_{2}}{3}}
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & 1 & -1  &\bigm| & -\frac{1}{3} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & \frac{3}{2} & -\frac{1}{2}  &\bigm| & -\frac{1}{2} \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3\text{R}_{2}}{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & \frac{7}{2} & -\frac{5}{2}  &\bigm| & -\frac{1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7\text{R}_{2}}{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & -\frac{2}{3} \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & -\frac{2}{3} \\
    0 & 1 & -1 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & -\frac{2}{3} \\
    0 & 1 & 0 &\bigm| & -\frac{1}{3} \\
    0 & 0 & 1 &\bigm| & -\frac{2}{3} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x_1=-\frac{2}{3} \\
x_2=\frac{1}{3} \\
x_3=\frac{2}{3} \\
\end{align}


In [9]:
# Pythonic solution:
import numpy as np

A=np.array([[2,3,-1,-1],[1,0,1,0],[-1,2,-2,0]])


A1 = RowScale(A,0,1/2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,-1)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,0,2,1)
print("A3")
print(A3,'\n')
A4 = RowScale(A3,1,-2/3)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,0,-3/2)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,1,2,-7/2)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,0,-1)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,1,1)
print("A8")
print(A8,'\n')


print("Solutions x_1, x_2, x_3:")
print(backwardSubstitution(A8))

A1
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]] 

A2
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [-1.   2.  -2.   0. ]] 

A3
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]] 

A4
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

A5
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

A6
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

A7
[[ 1.          0.          0.         -0.66666667]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

A8
[[ 1.          0.          0.         -0.66666667]
 [ 0.          1.          0.          0.33333333]
 [ 0.          0.          1.     

4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or neither both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>

The matrix deviates from row echelon form since the leading entry in row 3 appears to the left of the leading entry above it in row 2, instead of to the right.

b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>

While this matrix adheres to row echelon form by having the zero row (row 3) positioned below the non-zero rows (rows 1 and 2), it falls short of reduced row echelon form due to the leading entry in row 1 being 7, rather than 1.

c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>

This matrix attains reduced row echelon form as all rows exhibit leading entries of 1, and these entries are the sole non-zero values in their respective columns.

d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>

Confirming its status in reduced row echelon form, this matrix satisfies key conditions: a.) zero rows are positioned at the matrix's bottom below non-zero rows, b.) the leading entry in each non-zero row is to the right of the leading entry above it, c.) the leading entry in any non-zero row is 1, and d.) all entries in the column above and below a leading 1 are zero.

e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>

The matrix falls short of row echelon form due to the presence of the zero row (row 2) positioned above the non-zero row (row 3).

f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>

In deviating from row echelon form, this matrix exhibits leading entries in each row to the left of the leading entry above it, rather than to the right.

g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>

The matrix fails to meet row echelon form criteria as the leading entry in row 2 is not positioned to the right of the leading entry above it (row 1).


h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}

While this matrix aligns with row echelon form by placing the zero row (row 4) below non-zero rows (rows 1, 2, 3), it doesn't achieve reduced row echelon form due to the leading entry in row 1 being 2, not 1.

5. Solve the following systems of linear equations<br>
a.<br> 
\begin{align}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{align}
<br>
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & -1  &\bigm| & 0 \\
    4 & -1 & 1  &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & -5 & 5  &\bigm| & -18 \\
    4 & -1 & 1  &\bigm| & 4 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & -5 & 5  &\bigm| & -18 \\
    4 & -1 & 1  &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & -5 & 5  &\bigm| & -18 \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & -5 & 5  &\bigm| & -18 \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & -3  &\bigm| & 9 \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & -9 & 13  &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 9\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 4  &\bigm| & \frac{2}{5} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 4  &\bigm| & \frac{2}{5} \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1  &\bigm| & \frac{9}{5} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0  &\bigm| & \frac{19}{10} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0  &\bigm| & \frac{19}{10} \\
    0 & 1 & -1  &\bigm| & \frac{18}{5} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0  &\bigm| & \frac{19}{10} \\
    0 & 1 & 0  &\bigm| & \frac{37}{10} \\
    0 & 0 & 1  &\bigm| & \frac{1}{10} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x_1=-\frac{19}{10} \\
x_2=\frac{37}{10} \\
x_3=\frac{1}{10} \\
\end{align}


In [33]:
# Pythonic solution:
import numpy as np

A=np.array([[1,2,-3,9],[2,-1,-1,0],[4,-1,1,4]])


A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/5)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-2)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,9)
print("A5")
print(A5,'\n')
A6 = RowScale(A5,2,1/4)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,0,1)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,1,1)
print("A8")
print(A8,'\n')


print("Solutions x_1, x_2, x_3:")
print(backwardSubstitution(A8))

A1
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]] 

A2
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]] 

A3
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

A4
[[  1.    0.   -1.    1.8]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

A5
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

A6
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]] 

A7
[[ 1.   0.   0.   1.9]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]] 

A8
[[1.  0.  0.  1.9]
 [0.  1.  0.  3.7]
 [0.  0.  1.  0.1]] 

Solutions x_1, x_2, x_3:
[1.9 3.7 0.1]


b. <br>
\begin{align}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{align}
<br>
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1  &\bigm| & 1 \\
    -1 & 1 & -1  &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1  &\bigm| & 3 \\
    -1 & 1 & -1  &\bigm| & -1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1  &\bigm| & 3 \\
    -1 & 1 & -1  &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1  &\bigm| & 3 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1  &\bigm| & 3 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{2}{3} &\bigm| & 1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{2}{3} &\bigm| & 1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 3 & -1  &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{2}{3} &\bigm| & 1 \\
    0 & 1 & -\frac{1}{3}  &\bigm| & -1 \\
    0 & 0 & 0  &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$\therefore$ This linear system does not have any solutions.

In [45]:
# Pythonic solution:
import numpy as np

A=np.array([[1,2,0,-1],[2,1,1,1],[-1,1,-1,-1]])


A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,1)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/3)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-2)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,-3)
print("A5")
print(A5,'\n')


print("Solutions x, y, z:")
print(backwardSubstitution(A5))

A1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]] 

A2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]] 

A3
[[ 1.          2.          0.         -1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          3.         -1.         -2.        ]] 

A4
[[ 1.          0.          0.66666667  1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          3.         -1.         -2.        ]] 

A5
[[ 1.          0.          0.66666667  1.        ]
 [-0.          1.         -0.33333333 -1.        ]
 [ 0.          0.          0.          1.        ]] 

Solutions x, y, z:
No solution.


c. <br>
\begin{align}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{align}
<br>
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1  &\bigm| & 0 \\
    2 & 4 & 6  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1  &\bigm| & 0 \\
    2 & 4 & 6  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1  &\bigm| & 0 \\
    2 & 4 & 6  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{-\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 10 & 10  &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 10\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1  &\bigm| & 0 \\
    0 & 0 & 0  &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$\therefore$ This linear system has infinite solutions.


In [31]:
# Pythonic solution:
import numpy as np

A=np.array([[1,-3,-2,0],[-1,2,1,0],[2,4,6,0]])


A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,3)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,-10)
print("A5")
print(A5,'\n')


print("Solutions x_1, x_2, x_3:")
print(backwardSubstitution(A5))

A1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

A2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

A3
[[ 1. -3. -2.  0.]
 [-0.  1.  1. -0.]
 [ 0. 10. 10.  0.]] 

A4
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0. 10. 10.  0.]] 

A5
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0.  0.  0.  0.]] 

Solutions x_1, x_2, x_3:
Infinite solutions.


d. <br>
\begin{align}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{align}
<br>
<br>
Solution:
<br>
Reduced row echelon form:
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    1 & -1 & -1 & 1 &\bigm| & 0 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    1 & 1 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    1 & 1 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    1 & 1 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & -2 & -3 & 0 &\bigm| & -1 \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 2 & 1 &\bigm| & 1 \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{2} & 1 &\bigm| & \frac{1}{2} \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{1}{2} & 1 &\bigm| & \frac{1}{2} \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 1 & 1 & 0 &\bigm| & 1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{2} & 1 &\bigm| & \frac{1}{2} \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & -\frac{1}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{1}{2} & 1 &\bigm| & \frac{1}{2} \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & -\frac{1}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{-2\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & \frac{1}{2} & 1 &\bigm| & \frac{1}{2} \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{1}{2} & 1 &\bigm| & \frac{1}{2} \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 1 &\bigm| & 1 \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 1 &\bigm| & 1 \\
    0 & 1 & \frac{3}{2} & 0 &\bigm| & \frac{1}{2} \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \frac{3}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & -2 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + 2\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 1 &\bigm| & 1 \\
    0 & 1 & 0 & 0 &\bigm| & 2 \\
    0 & 0 & 1 & 0 &\bigm| & -1 \\
    0 & 0 & 0 & 0 &\bigm| & -1 \\
\end{pmatrix}
$
<br>
<br>
$\therefore$ This linear system does not have any solutions.

In [57]:
# Pythonic solution:
import numpy as np

A=np.array([[1,1,2,1,1],[1,-1,-1,1,0],[0,1,1,0,1],[1,1,0,1,2]])


A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,3,-1)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/2)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,-1)
print("A5")
print(A5,'\n')
A6 = RowScale(A5,2,-2)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,0,-1/2)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,1,-3/2)
print("A8")
print(A8,'\n')
A9 = RowAdd(A8,2,3,2)
print("A9")
print(A9,'\n')


print("Solutions w, x, y, z:")
print(backwardSubstitution(A9))

A1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]] 

A2
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0. -2.  0.  1.]] 

A3
[[ 1.   1.   2.   1.   1. ]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   1.   1.   0.   1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A4
[[ 1.   0.   0.5  1.   0.5]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   1.   1.   0.   1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A5
[[ 1.   0.   0.5  1.   0.5]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   0.  -0.5  0.   0.5]
 [ 0.   0.  -2.   0.   1. ]] 

A6
[[ 1.   0.   0.5  1.   0.5]
 [-0.   1.   1.5 -0.   0.5]
 [-0.  -0.   1.  -0.  -1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A7
[[ 1.   0.   0.   1.   1. ]
 [-0.   1.   1.5 -0.   0.5]
 [-0.  -0.   1.  -0.  -1. ]
 [ 0.   0.  -2.   0.   1. ]] 

A8
[[ 1.  0.  0.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [-0. -0.  1. -0. -1.]
 [ 0.  0. -2.  0.  1.]] 

A9
[[ 1.  0.  0.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [-0. -0.  1. -0. -1.]
 [ 0.  0.  0.  0. -1.]] 

Solutions w, x, y,

6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br>
<br>
Solution:<br>
a. The linear equation should be of the form $u_2+u_3=v$, and transform it into a linear equation:<br>
 $
    \begin{bmatrix} -1 \\ 3 \end{bmatrix} x + \begin{bmatrix} 2 \\ -6 \end{bmatrix} y = \begin{bmatrix} 1 \\ 2 \end{bmatrix} 
$<br>
b. We want to solve the system of linear equations:<br>
\begin{align}
-x+2y=1 \\
3x-6y=2
\end{align}<br>
c. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    -1 & 2 &\bigm| & 1 \\
    3 & -6 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{-\text{R}_{1}}
\begin{pmatrix}
    1 & -2 &\bigm| & -1 \\
    3 & -6 &\bigm| & 2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -2 &\bigm| & -1 \\
    3 & -6 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 3\text{R}_{1}}
\begin{pmatrix}
    1 & -2 &\bigm| & -1 \\
    0 & 0 &\bigm| & 5 \\
\end{pmatrix}
$
<br>
d. There is no solution.
<br>
e. $\therefore$ The vectors are not linear combinations of each other.
<br>

In [42]:
# Pythonic solution:
import numpy as np

A=np.array([[-1,2,1],[3,-6,2]])

A1 = RowScale(A,0,-1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,-3)
print("A2")
print(A2,'\n')


print("Solutions x, y:")
print(backwardSubstitution(A2))

A1
[[ 1. -2. -1.]
 [ 3. -6.  2.]] 

A2
[[ 1. -2. -1.]
 [ 0.  0.  5.]] 

Solutions x, y:
No solution.


b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>
<br>
Solution:<br>
a. The linear equation should be of the form $u_2+u_3=v$, and transform it into a linear equation:<br>
 $
    \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} x + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} y = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} 
$<br>
b. We want to solve the system of linear equations:<br>
\begin{align}
x=1 \\
x+y=2 \\
y=3
\end{align}<br>
c. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    1 & 1 &\bigm| & 2 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
   1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
   1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
   1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 &\bigm| & 0 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
   1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 &\bigm| & 0 \\
    0 & 1 &\bigm| & 0 \\
    0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br>
<br>
d. No solution exists. While examining the system of equations, we may determine that 
and $x = 1$ and $y = 1$ but it also impliess $y = 3$. $y$ has contradicting values, so $v$ cannot be expressed as a linear combination of $u_2$ and $u_3$.
<br>
e. $\therefore$ The vectors are not linear combinations of each other.
<br>

In [50]:
# Pythonic solution:
import numpy as np

A=np.array([[1,0,1],[1,1,2],[0,1,3]])


A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,1,2,-1)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,2,1/2)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,2,0,-1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,2,1,-1)
print("A5")
print(A5,'\n')


print("Solutions x, y:")
print(backwardSubstitution(A5))

A1
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 1. 3.]] 

A2
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 2.]] 

A3
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]] 

A4
[[1. 0. 0.]
 [0. 1. 1.]
 [0. 0. 1.]] 

A5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Solutions x, y:
No solution.


c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>
<br>
Solution:<br>
a. The linear equation should be of the form $u_2+u_3=v$, and transform it into a linear equation:<br>
 $
    \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} x + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} y = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} 
$<br>
b. We want to solve the system of linear equations:<br>
\begin{align}
x=3 \\
x+y=1 \\
x=-2
\end{align}<br>
c. Transform the system of linear equations to an augmented matrix:<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    1 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    0 & 1 &\bigm| & -2 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    0 & 1 &\bigm| & -2 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    0 & 1 &\bigm| & -2 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
d. We can say that $x = 3$ and $y = -2$, and the linear combination is $3u_2 - 2u_3 = v$.
<br>
e. $\therefore$ The vectors are linear combination of each other.
<br>

In [49]:
# Pythonic solution:
import numpy as np

A=np.array([[1,0,3],[1,1,1],[0,1,-2]])


A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,1,2,-1)
print("A2")
print(A2,'\n')


print("Solutions x, y:")
print(backwardSubstitution(A2))

A1
[[ 1.  0.  3.]
 [ 0.  1. -2.]
 [ 0.  1. -2.]] 

A2
[[ 1.  0.  3.]
 [ 0.  1. -2.]
 [ 0.  0.  0.]] 

Solutions x, y:
[ 3. -2.]


7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br>
<br>
Solution: <br>
a. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 1 \\ 1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ -1 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \end{bmatrix} \\
\end{equation}
<br>
\begin{align}
x+y=a \\
x-y=b \\
\end{align}
b. Transform the linear equation into its reduced echelon form:
$
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    1 & -1 &\bigm| & b \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & -2 &\bigm| & -a+b \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & -2 &\bigm| & -a+b \\
\end{pmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & 1 &\bigm| & \frac{a-b}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & 1 &\bigm| & \frac{a-b}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & \frac{a+b}{2} \\
    0 & 1 &\bigm| & \frac{a-b}{2} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x=\frac{a+b}{2} \\
y=\frac{a-b}{2} \\
\end{align}
$\therefore$ it is a span

b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br>
<br>
Solution: <br>
a. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \ +
    \textbf{z}\begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \\ c \end{bmatrix} \\
\end{equation}
<br>
\begin{align}
x+y=a \\
y+z=b \\
x+z=c \\
\end{align}
b. Transform the linear equation into its reduced echelon form:
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    1 & 0 & 1 &\bigm| & c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & \frac{a+b-c}{2} \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x=\frac{a-b+c}{2} \\
y=\frac{a+b-c}{2} \\
z=\frac{-a+b+c}{2} \\
\end{align}
$\therefore$ it is a span

c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br>
<br>
Solution: <br>
a. Write the span in terms of a linear equation:
\begin{equation}
    \textbf{x}\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} \ +
    \textbf{y}\begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} \ +
    \textbf{z}\begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix} \ =
    \begin{bmatrix} a \\ b \\ c \end{bmatrix} \\
\end{equation}
<br>
\begin{align}
x+y=a \\
y+z=b \\
x+z=c \\
\end{align}
b. Transform the linear equation into its reduced echelon form:
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    1 & 0 & 1 &\bigm| & c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & -a+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & -1 &\bigm| & a-b \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & -a+b+c \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & \frac{a-b+c}{2}  \\
    0 & 1 & 1 &\bigm| & \frac{a+b-c}{2} \\
    0 & 0 & 1 &\bigm| & \frac{-a+b+c}{2} \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
x=\frac{a-b+c}{2} \\
y=\frac{a+b-c}{2} \\
z=\frac{-a+b+c}{2} \\
\end{align}
$\therefore$ it is a span

8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}

Set their sum to 0
\begin{equation}
w\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix} +
x\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix} +
y\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix} +
z\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix} = 
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}
\end{equation}

Transform into reduced row echelon form
<br>
$
\begin{pmatrix}
    3 & -1 & 1 & -1 &\bigm| & 0 \\
    -1 & 2 & 1 & -1 &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    -1 & 2 & 1 & -1 &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    -1 & 2 & 1 & -1 &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    1 & 1 & 3 & 1 &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    -1 & -1 & 1 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{1}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & \frac{5}{3} & \frac{4}{3} & -\frac{4}{3} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{3}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -\frac{1}{3} & \frac{1}{3} & -\frac{1}{3} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & \frac{4}{3} & \frac{8}{3} & \frac{4}{3} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{4}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & \frac{8}{5} & \frac{12}{5} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & \frac{8}{5} & \frac{12}{5} &\bigm| & 0 \\
    0 & -\frac{4}{3} & \frac{4}{3} & \frac{8}{3} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + \frac{4}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & \frac{8}{5} & \frac{12}{5} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & \frac{8}{5} & \frac{12}{5} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{5}{8}2\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & \frac{3}{5} & -\frac{3}{5} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{5}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & \frac{4}{5} & -\frac{4}{5} &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \frac{4}{5}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & \frac{12}{5} & \frac{8}{5} &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \frac{12}{5}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & -2 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -\frac{3}{2} &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \frac{3}{2}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -2 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 2\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & \frac{3}{2} &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{3}{2}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
w=0 \\
x=0 \\
y=0 \\
z=0 \\
\end{align}
$\therefore$ Since all scalars are 0, the vectors are linearly independent.

In [67]:
# Pythonic solution:
import numpy as np

A=np.array([[3,-1,1,-1,0],[-1,2,1,-1,0],[1,1,3,1,0],[-1,-1,1,3,0]])


A1 = RowScale(A,0,1/3)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,1)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,0,2,-1)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,0,3,1)
print("A4")
print(A4,'\n')
A5 = RowScale(A4,1,3/5)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,1,0,1/3)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,1,2,-4/3)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,1,3,4/3)
print("A8")
print(A8,'\n')
A9 = RowScale(A8,2,5/8)
print("A9")
print(A9,'\n')
A10 = RowAdd(A9,2,0,-3/5)
print("A10")
print(A10,'\n')
A11 = RowAdd(A10,2,1,-4/5)
print("A11")
print(A11,'\n')
A12 = RowAdd(A11,2,3,-12/5)
print("A12")
print(A12,'\n')
A13 = RowScale(A12,3,-1/2)
print("A13")
print(A13,'\n')
A14 = RowAdd(A13,3,0,3/2)
print("A14")
print(A14,'\n')
A15 = RowAdd(A14,3,1,2)
print("A15")
print(A15,'\n')
A16 = RowAdd(A15,3,2,-3/2)
print("A16")
print(A16,'\n')

print("Solutions w, x, y, z:")
print(backwardSubstitution(A16))

A1
[[ 1.         -0.33333333  0.33333333 -0.33333333  0.        ]
 [-1.          2.          1.         -1.          0.        ]
 [ 1.          1.          3.          1.          0.        ]
 [-1.         -1.          1.          3.          0.        ]] 

A2
[[ 1.         -0.33333333  0.33333333 -0.33333333  0.        ]
 [ 0.          1.66666667  1.33333333 -1.33333333  0.        ]
 [ 1.          1.          3.          1.          0.        ]
 [-1.         -1.          1.          3.          0.        ]] 

A3
[[ 1.         -0.33333333  0.33333333 -0.33333333  0.        ]
 [ 0.          1.66666667  1.33333333 -1.33333333  0.        ]
 [ 0.          1.33333333  2.66666667  1.33333333  0.        ]
 [-1.         -1.          1.          3.          0.        ]] 

A4
[[ 1.         -0.33333333  0.33333333 -0.33333333  0.        ]
 [ 0.          1.66666667  1.33333333 -1.33333333  0.        ]
 [ 0.          1.33333333  2.66666667  1.33333333  0.        ]
 [ 0.         -1.33333333  1.33333

b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}

Set their sum to 0
\begin{equation}
w\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix} +
x\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix} +
y\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix} +
z\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix} = 
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}
\end{equation}

Transform into reduced row echelon form
<br>
$
\begin{pmatrix}
    0 & 0 & 0 & 4 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    1 & 1 & 1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{4}}
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 2 & 2 & 2 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 3 & 3 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 4 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
w=0 \\
x=0 \\
y=0 \\
z=0 \\
\end{align}
$\therefore$ Since all scalars are 0, the vectors are linearly independent.

In [64]:
# Pythonic solution:
import numpy as np

A=np.array([[0,0,0,4,0],[0,0,3,3,0],[0,2,2,2,0],[1,1,1,1,0]])


A1 = RowSwap(A,0,3)
print("A1")
print(A1,'\n')
A2 = RowSwap(A1,1,2)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,1/2)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-1)
print("A4")
print(A4,'\n')
A5 = RowScale(A4,2,1/3)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,2,1,-1)
print("A6")
print(A6,'\n')
A7 = RowScale(A6,3,1/4)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,3,2,-1)
print("A8")
print(A8,'\n')


print("Solutions w, x, y, z:")
print(backwardSubstitution(A8))

A1
[[1. 1. 1. 1. 0.]
 [0. 0. 3. 3. 0.]
 [0. 2. 2. 2. 0.]
 [0. 0. 0. 4. 0.]] 

A2
[[1. 1. 1. 1. 0.]
 [0. 2. 2. 2. 0.]
 [0. 0. 3. 3. 0.]
 [0. 0. 0. 4. 0.]] 

A3
[[1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 3. 3. 0.]
 [0. 0. 0. 4. 0.]] 

A4
[[1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 3. 3. 0.]
 [0. 0. 0. 4. 0.]] 

A5
[[1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 4. 0.]] 

A6
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 4. 0.]] 

A7
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

A8
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]] 

Solutions w, x, y, z:
[0. 0. 0. 0.]


c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}

Set their sum to 0
\begin{equation}
w\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix} +
x\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix} +
y\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix} +
z\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix} = 
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}
\end{equation}

Transform into reduced row echelon form
<br>
$
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    -1 & 1 & 0 & 1 &\bigm| & 0 \\
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} \leftrightarrow \text{R}_{3}}
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & -1 & 1 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 1 & -1 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & -1 & 2 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 1 & -1 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & -1 & 2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & -1 & 2 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & -1 & 2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 3 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 3 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & -2 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 2\text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & -1 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
$
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{4}}
\begin{pmatrix}
    1 & 0 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & 0 & 0 &\bigm| & 0 \\
    0 & 0 & 1 & 0 &\bigm| & 0 \\
    0 & 0 & 0 & 1 &\bigm| & 0 \\
\end{pmatrix}
$
<br>
<br>
\begin{align}
w=0 \\
x=0 \\
y=0 \\
z=0 \\
\end{align}
$\therefore$ Since all scalars are 0, the vectors are linearly independent.

In [66]:
# Pythonic solution:
import numpy as np

A=np.array([[1,-1,1,0,0],[-1,1,0,1,0],[1,0,1,-1,0],[0,1,-1,1,0]])


A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-1)
print("A2")
print(A2,'\n')
A3 = RowSwap(A2,1,2)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,3,-1)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,2,0,-1)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,2,3,1)
print("A7")
print(A7,'\n')
A8 = RowScale(A7,3,1/3)
print("A8")
print(A8,'\n')
A9 = RowAdd(A8,3,0,2)
print("A9")
print(A9,'\n')
A10 = RowAdd(A9,3,1,1)
print("A10")
print(A10,'\n')
A11 = RowAdd(A10,3,2,-1)
print("A11")
print(A11,'\n')

print("Solutions w, x, y, z:")
print(backwardSubstitution(A11))

A1
[[ 1. -1.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 1.  0.  1. -1.  0.]
 [ 0.  1. -1.  1.  0.]] 

A2
[[ 1. -1.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  1. -1.  1.  0.]] 

A3
[[ 1. -1.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  1. -1.  1.  0.]] 

A4
[[ 1.  0.  1. -1.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  1. -1.  1.  0.]] 

A5
[[ 1.  0.  1. -1.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0. -1.  2.  0.]] 

A6
[[ 1.  0.  0. -2.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0. -1.  2.  0.]] 

A7
[[ 1.  0.  0. -2.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  0.  3.  0.]] 

A8
[[ 1.  0.  0. -2.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  0.  1.  0.]] 

A9
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 0.  0.  0.  1.  0.]] 

A10
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]] 

A11
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]